### ISSUE TITLE
adding a GTM energy container trait crashes the game

### ISSUE THREAD

**Issue by iCantComeUpWithAnything** [Low-Drag-MC/Multiblocked2#11]
tested with:
LowDragLib, GregTech Modern, MultiBlocked 2, Configuration
[crash-2024-10-01_16.48.07-client.txt](https://github.com/user-attachments/files/17211592/crash-2024-10-01_16.48.07-client.txt)

**Comment by Yefancy** [comment]
thanks for your report. it got fixed in the 1.0.6+
