### ISSUE TITLE
[1.0.7] Cannot load mod without KubeJS installed

### ISSUE THREAD

**Issue by MapperTV** [Low-Drag-MC/Multiblocked2#13]
Version used: multiblocked2-1.20.1-1.0.7.jar
Logs: https://pastebin.com/zHy37W2n

With 1.0.7 it seems that KubeJS is required to start. 

`Caused by 0: java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/event/EventJS`

Either KubeJS should be marked as required dependency on CurseForge or KubeJS should not be required to start the game (I think it's bette as not everyone needs it).

**Comment by Yefancy** [comment]
fixed in the 1.0.7.a
