### ISSUE TITLE
Multiblock not notifying neighbors once formed

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#15]
## Description
This is a reminder of the issue posted in this [Discord message](https://discord.com/channels/980360897354682389/980361468652437527/1291117854678323313).

## Relication
In order to replicate, you can use a Blender multiblock from the recent video tutorial regarding multiblocks.
1. Remove the controller
2. Place a Mekanism pipe next to the input hatch
3. Place the controller back in place

### Expected behavior
Pipe connecting to the input hatch (which is a capability proxy)
### Actual behavior
Pipe remains disconnected. It reconnects once you remove the hatch and place it back again.

## Cause
It looks like this issue happens due to multiblock not notifying neighbors once it’s formed. There might be other reasons, but this is the most apparent one to me.

**Comment by Yefancy** [comment]
whats your version? its not fixed in the latest mbd yet?

**Comment by andriihorpenko** [comment]
I’ll test it with the latest mbd2 and get back to you.

**Comment by andriihorpenko** [comment]
Yep, can confirm that the issue was resolved, just wasn't listed in the changelog.
