### ISSUE TITLE
[1.0.7] Disabling AO doesn't disable it on neighboring blocks

### ISSUE THREAD

**Issue by MapperTV** [Low-Drag-MC/Multiblocked2#16]
Version used: multiblocked2-1.20.1-1.0.7.jar

I wanted to disable AO on a test machine to avoid shadows appearing around it since it uses a transparent texture (glass) so I unchecked the setting `Use AO` as it is on by default.

![image](https://github.com/user-attachments/assets/0b6adf76-eef0-45ff-9d4c-adb672503503)

However, after reloading using /mbd2 reload_machine_projects or after restarting the game, the block still has AO enabled on the blocks around:

![image](https://github.com/user-attachments/assets/601c69dd-3e4a-463c-b7e7-cb1d59ff5f2c)

For what I can see, it only disables the shading on the block itself (left = custom machine with AO unchecked, right = vanilla stair block):

![image](https://github.com/user-attachments/assets/ff0c414b-c194-41a2-944c-809c8c4de2ec)
Enabling AO will make the machine render like the oak stair block.

In Minecraft the shading is something different than ambient occlusion (see [Block Models](https://minecraft.wiki/w/Model#Block_models)) so this is confusing. Shouldn't unchecking `Use AO` actually disable AO and not the shading?

**Comment by Yefancy** [comment]
its not a bug, I will add supports for control `Propagates Skylight Down` and `Shade Brightness`

**Comment by Yefancy** [comment]
you can fix it by set a block as transparent block in the latest mbd2
