### ISSUE TITLE
Client crash from the in-world preview

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#17]
## Description
New version introduced a feature for in-world previewing multiblock structure. This feature may cause a crash while Shift+RMB clicking a controller. 
Note that this happens irregularity and I am unable to replicate it at a 100% rate.

## Useful info
MDB version: 1.0.7.c
Project files: [mbd2.zip](https://github.com/user-attachments/files/17270208/mbd2.zip)
Crash report: [message.txt](https://github.com/user-attachments/files/17270193/message.txt)

**Comment by Yefancy** [comment]
fixed in 1.0.7.d+
