### ISSUE TITLE
Predicates are transparent in EMI

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#18]
## Description
Predicates are not displayed in EMI. Items are transparent, however, tooltips are rendering fine.

## Project
[ldlib.zip](https://github.com/user-attachments/files/17275534/ldlib.zip)

## Screenshot
<img width="543" alt="image" src="https://github.com/user-attachments/assets/98a689b0-43de-4e5f-be71-a128516be29c">

## Mod list
<img width="328" alt="image" src="https://github.com/user-attachments/assets/2080d7fd-ae34-44a4-9673-2801ceeb451f">

**Comment by andriihorpenko** [comment]
_This message was copied from [Discord](https://discord.com/channels/980360897354682389/980361468652437527/1315346907752566884)_

So MDB uses `CycleItemStackHandler` for predicates and candidates. LDLib has `ModularEmiRecipe` which is used for multiblock category. When `ModularEmiRecipe#addWidgets` is called, it calls this line:
```java
slotW.setHandlerSlot(IItemTransfer.EMPTY, 0);
```
Essentially it nukes `CycleItemStackHandler` and replaces it with `IItemTransfer.EMPTY`
Therefore, any calls to `getStackInSlot` return empty item stack

How I tested it:
```java
@Mixin(ModularEmiRecipe.class)
public abstract class ModularEmiRecipeMixin {
    @Redirect(method = "addWidgets", at = @At(value = "INVOKE", target = "Lcom/lowdragmc/lowdraglib/gui/widget/SlotWidget;setHandlerSlot(Lcom/lowdragmc/lowdraglib/side/item/IItemTransfer;I)Lcom/lowdragmc/lowdraglib/gui/widget/SlotWidget;", remap = false), remap = false)
    private SlotWidget issue18(SlotWidget instance, IItemTransfer itemHandler, int slotIndex) {
        return instance;
    }
}
```

**Comment by screret** [comment]
you want to add a special case for that class to be ignored in the handler replacement, as just not doing it will break other plugins (GT) quite badly.
