### ISSUE TITLE
JEI pages for multiblock structure and recipes are missing

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#19]
## Description
There are no longer JEI pages neither for multiblock structure, nor for multiblock recipes.
However, they are present when EMI is installed.

## Replication
1. Install the mods and multiblock project listed below.
2. Try pressing U to view a multiblock structure - it WON'T show up. 
3. Install EMI and restart the game
4. Press U to view a multiblock structure - it WILL show up.

**Note**: the project below does not include recipes. I think fixing JEI for multiblock structure preview should fix recipes as well.

## Project
[ldlib.zip](https://github.com/user-attachments/files/17275608/ldlib.zip)

## Mod list without EMI
<img width="328" alt="image" src="https://github.com/user-attachments/assets/b0f3a34e-a80b-4403-8b02-273dec5a072e">

## Mod list with EMI
<img width="306" alt="image" src="https://github.com/user-attachments/assets/50073074-cd51-4a62-87a0-e48f565bf8c2">

**Comment by Yefancy** [comment]
bump up your jei to the 15.17.0.74+

**Comment by andriihorpenko** [comment]
That did it, CF installs release instead of beta versions by default.
I think adding minimum required version of JEI to mods.toml could prevent similar reports in the future.

**Comment by Yefancy** [comment]
jei api changes too frequently

**Comment by Yefancy** [comment]
May I close it?

**Comment by andriihorpenko** [comment]
Sure, the integration works just fine with the new version of JEI.
