### ISSUE TITLE
FE tooltip displays incorrect decimal values

### ISSUE THREAD

**Issue by MapperTV** [Low-Drag-MC/Multiblocked2#26]
Version used: 1.0.8a

Tooltip for energy storage can render weird decimal values:

![image](https://github.com/user-attachments/assets/685d16a6-fe87-4e9e-90b0-8fb9720c0cf2)

In this case the craft is set to consume 20FE/t for 100 ticks.

Technically no decimal value should appear since only integer values are used. Unless calculations are done faster than a Minecraft tick?

**Comment by Yefancy** [comment]
fixed since 1.0.9
