### ISSUE TITLE
[1.0.8a] Cables / pipes randomly disconnect and reconnect

### ISSUE THREAD

**Issue by MapperTV** [Low-Drag-MC/Multiblocked2#27]
Version used: 1.0.8a

When a machine works, cables or tubes sometimes disconnect and reconnect quickly multiple times. Also, when the machine stops working because it lacks an ingredient to complete a craft (like energy), the cables or tubes can disconnect.

![2024-10-08_17 42 43](https://github.com/user-attachments/assets/91e9c543-40bc-4287-a318-072acf7eca91)

Here is a video showing the tube being disconnected after the machine ran out of energy, reconnecting once the energy is back, disconnecting again when power is out. The energy cable also disconnect at some point, preventing energy to enter when replacing the solar panel. And you can see around 0:27 the cable and tube flickering because of the quick disconnects.

https://streamable.com/466j7i

Note: the fact the pressurized tubes are not connected to another inventory such as a tank doesn't matter, I tried with and the problem persists.

Here are the files for this machine: [mbd2.zip](https://github.com/user-attachments/files/17299641/mbd2.zip)
Note: while I was writing this report, my machine file suddenly stopped working, making the game crash (error related to Mekanism infuse gas). i will make another report for it. No idea if you will be able to load it on your end.

**Comment by Yefancy** [comment]
fixed since 1.0.9
