### ISSUE TITLE
[1.0.8a] Machine file cannot be loaded (Invalid chemical for tank: mekanism:diamond 500)

### ISSUE THREAD

**Issue by MapperTV** [Low-Drag-MC/Multiblocked2#28]
Version used: 1.0.8a
Crash report: [crash-2024-10-08_17.54.46-client.txt](https://github.com/user-attachments/files/17299677/crash-2024-10-08_17.54.46-client.txt)
Machine files: [mbd2.zip](https://github.com/user-attachments/files/17299681/mbd2.zip)

While writing the [previous issue](https://github.com/Low-Drag-MC/Multiblocked2/issues/27) about disconnecting pipes, I tried to load my machine file `double_infuser.sm` and it crashed the game with the error: 
`java.lang.RuntimeException: Invalid chemical for tank: mekanism:diamond 500`

The only thing I did was restarting the game at some point while doing my tests with the pipes. The machine doesn't use `mekanism:diamond` infuse type in the slot filters or the recipe, only `mekanism:refined_obsidian` and `mekanism:gold`.

The recipe file `double_infuser_recipe.rt` can be loaded fine.

**Comment by Warbringer12** [comment]
i got somewhat of a same thing but i didn't put the set the chemical tank to hydrogen for the one it crashes on..
I set it for oxygen

error: java.lang.RuntimeException: Invalid chemical for tank: mekanism:hydrogen 500

was trying to open my oxygen gas output in the editor

**Comment by Yefancy** [comment]
after setup a filter, it will crash, will be fixed in the next version

**Comment by Yefancy** [comment]
fixed since 1.0.9
