### ISSUE TITLE
Incompatibility with Lodestone mod

### ISSUE THREAD

**Issue by yellowcake3d** [Low-Drag-MC/Multiblocked2#3]
Forge 1.20.1

Installed mods:
Multiblocked2 1.0.3
LowDragLib 1.0.28
Lodestone 1.20.1-1.6.2.1

When installed with lodestone, this message is being spammed in the log:

`[14:53:24] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.`

**Comment by Yefancy** [comment]
any idea when it happens? for example, if and only if the editor is oppened or it will always spam in the log?

**Comment by yellowcake3d** [comment]
It starts spamming the log when logged into the world, and spams always

**Comment by Yefancy** [comment]
it only happens if an only if both mbd + ldlib + lodestone installed? how about ldlib + lodastone? only ldlib + mbd? only lodestone

**Comment by yellowcake3d** [comment]
Just checked again, it looks to be the LowDragLib problem and not multiblocked2 problem, it starts spamming with only LowDragLib and lodestone

Lodestone by itself with no mods doesn't cause this bug

**Comment by Yefancy** [comment]
I can't seem to reproduce it in my dev env. could you provide all your mods. as awell as forge version?

**Comment by Yefancy** [comment]
Lodestone is just a lib right? dont you install other mods?

**Comment by yellowcake3d** [comment]
I had other mods but for the test I used only lodestone. I am trying to reproduce it now again with the same mods but can't anymore.. Might have been a problem with my machine back when I tested it, sorry for that
