### ISSUE TITLE
[Suggestion] Adding Tags to Predicates

### ISSUE THREAD

**Issue by birbs2** [Low-Drag-MC/Multiblocked2#31]
It would be very helpful to add tag capabilities to predicates, so you can add tags along with specific blocks. This feature would make it easier to create large predicates with many blocks. For example: "#chipped:dirt" instead of "chipped:unamused_dirt", "chipped:cobbled_dirt"... etc.

**Comment by Yefancy** [comment]
good idea

**Comment by Yefancy** [comment]
Added
