### ISSUE TITLE
[bug] tooltips in mbd2 machine's gui render behind the emi item menu.

### ISSUE THREAD

**Issue by QLNPLUS** [Low-Drag-MC/Multiblocked2#36]
tooltips in mbd2 machine's gui render behind the emi item menu.
![image](https://github.com/user-attachments/assets/7c3e5106-e577-437f-ae21-6e502e1a909a)

**Comment by QLNPLUS** [comment]
在mbd2制作的机器中，物品的tooltips会渲染在emi下方

**Comment by Yefancy** [comment]
bump up the ldlib to the 1.0.33.a+ to fix it
