### ISSUE TITLE
KubeJS's machineData method has Bug

### ISSUE THREAD

**Issue by zhichaoxi2006** [Low-Drag-MC/Multiblocked2#37]
![image](https://github.com/user-attachments/assets/75fc861e-8bec-4404-99f7-f0c11320ae9b)
这段代码在游戏中理应是输出1.0f，然而：
![image](https://github.com/user-attachments/assets/f22529ff-2d80-45be-a6b1-933c93535d0c)
输出为1.0d，数据类型并不正确。

然后我在KubeJS写了另一段代码
![image](https://github.com/user-attachments/assets/8847a7e8-99ea-4175-beac-01aae4571f62)
输出为预期的1.0f
![image](https://github.com/user-attachments/assets/226b757f-ae57-4579-bfa1-61a4c91c765e)

**Comment by Yefancy** [comment]
display text is converted as json. but the real internal data should still be the `float` I think

**Comment by Yefancy** [comment]
will fix display later
