### ISSUE TITLE
Forge OBJ Models - Enhancement 

### ISSUE THREAD

**Issue by ColinVaughn** [Low-Drag-MC/Multiblocked2#38]
would be nice to add support for forge OBJ along with geckolib.

**Comment by Yefancy** [comment]
it should be considiered by geckolib.

**Comment by ColinVaughn** [comment]
geckolib doesn't support OBJ and it's quite limiting for some modelers as they are stuck to 22.5 degree limit

**Comment by Yefancy** [comment]
Yeah But it's not the things that mbd should cope with
