### ISSUE TITLE
Create Rotation Axis Incorrect

### ISSUE THREAD

**Issue by iglee42** [Low-Drag-MC/Multiblocked2#39]
Hi, I love your mod, but I have a problem with the Create compat, I put in the machine config that the rotation axis should be at the top but even if I change the machine config it's stay on the north face 

https://github.com/user-attachments/assets/8bc195c7-04c7-402d-bf85-4c57ce7cd5a6

https://github.com/user-attachments/assets/477f265d-b48b-4217-b75e-7b05642c42da

![image](https://github.com/user-attachments/assets/3db37d54-e341-4dad-b5bb-46a730181fb6)

**Comment by iglee42** [comment]
Also when I "plug" a hand crank which produces 256su the machine finds only 32su
![2024-10-18_23 47 23](https://github.com/user-attachments/assets/bfabdf5a-6532-4244-b154-5f418bc38448)

![2024-10-18_23 47 20](https://github.com/user-attachments/assets/f513e6ef-6d3c-43b5-8d2b-5aef8ce2394c)

**Comment by Yefancy** [comment]
could you show me your mbd folder?

**Comment by Yefancy** [comment]
btw, create machine's stress is according to the rpm and torque(cpactity). 
stress = rpm * torque.
hand crank does have it max stress,
but also rpm.

**Comment by iglee42** [comment]
[mbd2.zip](https://github.com/user-attachments/files/17444584/mbd2.zip)

**Comment by iglee42** [comment]
> btw, create machine's stress is according to the rpm and torque(cpactity). stress = rpm * torque. hand crank does have it max stress, but also rpm.

I make Create addon so here's how I think it can be do :

I don't think this is a good way to do that because normally create machines consume the "stress multiplier * rpm", but with mbd2 the recipe ask a stress value, I think it should ask for a minimum RPM or just "have rotation" instead of stress.

The stress impact can thus be calculated with the RPM * torque

And you should do the duration of the recipe is reduce according to rpm

**Comment by Yefancy** [comment]
yeah, but your idea only suits for the create addon. mbd is designed for the universal recipe logic, we cant reduce duration via rpm so far.

**Comment by iglee42** [comment]
I see but can you at least add an option to do that ?
And for the stress calculation I don't see what the problem is with applying the same calculation as Create

**Comment by Yefancy** [comment]
will be considered

**Comment by iglee42** [comment]
Ok and for the rotation axis ?

**Comment by Yefancy** [comment]
ah, its a bug, will fix it in few mins

**Comment by iglee42** [comment]
Ok cool

**Comment by Yefancy** [comment]
btw, I'd like to add the rpm supports in this update as well. instead of set rpm as an input or ouput directly, I prefer to add a new condition that set up a rpm range. what do you think about it?

**Comment by iglee42** [comment]
I think it can be a good idea

**Comment by Yefancy** [comment]
emm, probably, add the rpm as an ingredietn is better. I will add the condition first, and add the rpm ingredient when I have time.

**Comment by iglee42** [comment]
ok

**Comment by iglee42** [comment]
Also I find another bug, when you reload machine project, the slots are bugged and you need to replace the machine to make them word
Also it's just a personnal idea, I could be cool to have an event which is called when an item is dropped on the top of the machine

**Comment by Yefancy** [comment]
its not a bug, just you have to repalce your machine technically.

**Comment by iglee42** [comment]
Ok and for the item event ?

**Comment by Yefancy** [comment]
you can listen to the drop event and handle it yourself

**Comment by iglee42** [comment]
It's not the same thing no ? It says it when the machine is broken and it drop items

**Comment by Yefancy** [comment]
recipe outputs?

**Comment by iglee42** [comment]
Nop I want to do when a item is dropped on the machine it's absorbed by the machine into the input slot

**Comment by Yefancy** [comment]
1. listen to the sever tick event.
2. check entities (with itementtiy predicate)
3. create itemstack and transfer it into you internal slots

**Comment by iglee42** [comment]
There is an event to check entites ?

**Comment by Yefancy** [comment]
there are such nodes

**Comment by iglee42** [comment]
Ok I didn't see it

**Comment by iglee42** [comment]
Also it is normal that when I use an extract item node, I can't set the amount to 64

**Comment by Yefancy** [comment]
not sure, when check it when I have time. btw shall we move to the dc?

**Comment by iglee42** [comment]
dc ?

**Comment by Yefancy** [comment]
discord, my mail app keeps ringing

**Comment by iglee42** [comment]
Yeah I think it's better, here's my discord iglee42

**Comment by Yefancy** [comment]
I mean could you please go to the mbd2 discord.....
