### ISSUE TITLE
Custom Recipe Type Becomes Disabled Due to Conflict with KubeJS

### ISSUE THREAD

**Issue by RomeUnion373** [Low-Drag-MC/Multiblocked2#4]
## Environment

- Minecraft 1.20.1
- Forge 47.3.0

- Architectury 9.2.14
- JEI 15.19.5.99
- KubeJS 2001.6.5-build.14
- ldlib 1.0.28.c
- multiblocked2 1.0.3
- rhino 2001.2.3-build.6

## Steps to Reproduce

1. Create any Recipe Type Project and save it (I followed a YouTube tutorial video).
2. In the KubeJS server_scripts file, create any JavaScript file and call the ServerEvents.recipes method. 
3. Save the file and reload. The issue can be reproduced regardless of whether anything is written inside the function or not.

## Result
Custom recipe types no longer appear in the JEI tab. Additionally, specifying a recipe type on the machine side does not work.

![2024-09-24_22 53 49](https://github.com/user-attachments/assets/42f4e550-9195-44ba-92e8-1d7f0dc4d623)
![スクリーンショット 2024-09-24 225401](https://github.com/user-attachments/assets/2bda3a3c-2446-486f-b518-fb2a2b430f25)

I believe this mod is the most creative support mod for modpack creators that I have ever seen. Thank you for releasing this wonderful mod. Best regards.

### Additional Note
This is just a joke, right??????????????
![スクリーンショット 2024-09-24 223959](https://github.com/user-attachments/assets/291b783f-3511-46a5-b9fb-018fb3c562ad)

**Comment by Yefancy** [comment]
dw, mbd2 will add kubejs for sure, not yet

**Comment by RomeUnion373** [comment]
Got it, thank you. I’m looking forward to future updates.

**Comment by Yefancy** [comment]
fixed in the latest mbd2
