### ISSUE TITLE
[BUG] Can not transfer item into machine in server

### ISSUE THREAD

**Issue by QLNPLUS** [Low-Drag-MC/Multiblocked2#41]
在服务器中使用mbd2制作的机器，打开机器的gui界面，背包中的物品和机器里的物品均无法被交互，移动（无法从一个物品栏位移动到别的物品栏位、机器的物品栏和背包物品栏均不行）。但是可以使用漏斗流入物品，单人模式正常。

游戏版本：1.20.1 forge 47.3.0
modlist：
ldlib-forge-1.20.1-1.0.30.b.jar
multiblocked2-1.20.1-1.0.10.jar

**Comment by QLNPLUS** [comment]
https://github.com/user-attachments/assets/11f7aa08-9477-461e-a985-23eb82b4ce20

**Comment by Yefancy** [comment]
半小时后，更新ldlib到1.0.30.d
