### ISSUE TITLE
Game crashes when I put a set the model when creating a multiblock

### ISSUE THREAD

**Issue by PI-32** [Low-Drag-MC/Multiblocked2#42]
its probably a really stupid issue that is really easy to fix on my end, my guess is that I made the model for it improperly and I don't have the knowledge on how to do so.

here is the error that the minecraft launcher gives me when I crash:
The game crashed whilst mouseclicked event handler
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: mbd2:geo/Large Furnace.geo.json

any help is appreciated, thanks.

**Comment by Yefancy** [comment]
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: mbd2:geo/Large Furnace.geo.json

**Comment by Yefancy** [comment]
Lowercase without spaces

**Comment by PI-32** [comment]
what, im confused.

**Comment by Yefancy** [comment]
Your file name is Large Furnace.geo.json

**Comment by Yefancy** [comment]
Could you read my comments carefully

**Comment by PI-32** [comment]
Ohhhhh, that flew right over my head. You phrased it in a way that confused me lol, sorry I am a bit slow at times. it worked lol, thanks for the help.
