### ISSUE TITLE
recipes not properly linking to multiblock machine

### ISSUE THREAD

**Issue by StarkDetail023** [Low-Drag-MC/Multiblocked2#44]
I made a recipe for my multiblock and it shows up in jei just fine, but when put the required items into the multiblock nothing happens.
pls help.

**Comment by Yefancy** [comment]
**FAQ: Why my recipe doesn't work?**

1. Use the mbd gadgets to debug your recipes:
  -  switch the mode to the recipe debugger
  -  open the ui to select a mbd recipe by id
  -  right click the machine
  -  will send you a chat message about whether the reicp can be handled, if not, will also tell you the reason

2. Did you set a correct `Recipe Handle IO` for your traits? 
3. Did you assign a `recipetye` to your machine?
4. Traits support the recipe requirements? (e.g. energy storage's capacity >= recipe requires)

**Comment by StarkDetail023** [comment]
I did all of those except the first one, what is and where are the mbd gadgets?

**Comment by Yefancy** [comment]
its an item. it has been added for a while. whats your version?

**Comment by StarkDetail023** [comment]
1.20.1, I had no idea that there was such an item.

**Comment by Yefancy** [comment]
obviously Im asking for your mod version......

**Comment by StarkDetail023** [comment]
oh my misunderstanding, 1-1.0.10 im pretty sure

**Comment by Yefancy** [comment]
there is such item, Im pretty sure

**Comment by Yefancy** [comment]
could you please search `gadget` in your creative searchbar with a screenshot. I dont think you can't find it

**Comment by StarkDetail023** [comment]
oh, I saw this and thought it was meant to assemble the multiblocks. Did not know there were multiple modes.

**Comment by StarkDetail023** [comment]
![image_2024-10-21_203013500](https://github.com/user-attachments/assets/3e32c9ca-3dcf-42e4-898b-107944d79194)
I used it and it says im missing coal and iron inputs, is there a way to bind specific recipe inputs and outputs to multiblock inputs and outputs?

**Comment by Yefancy** [comment]
1. did you have item traits?
2. did you set it `reicpe hadnler IO` to the IN/BOTH?
3. did you bind it to a ui slot with correct ui id?(trait id: `ABC` -> slot id: `ui:ABC_0`)
4. if you are using the part as inputs. did you enable the `art settings` for your part machien?

**Comment by StarkDetail023** [comment]
I'm not sure by what you mean on the fourth point

**Comment by Yefancy** [comment]
are you using the parts as inputs for you multiblock?

**Comment by StarkDetail023** [comment]
im not sure by what you mean by "parts". do you mean items for inputs?

**Comment by Yefancy** [comment]
fine, I suppose you dont know what the parts are. so all traits are added in the controller block?

**Comment by Yefancy** [comment]
share me you mbd2 folder, I can help check it later

**Comment by StarkDetail023** [comment]
sorry I'm just not familiar with the terminology that you are using.

**Comment by Yefancy** [comment]
I mean could you send me your project files.

**Comment by Yefancy** [comment]
I think you are too new to the concept of mbd2, maybe you can try creating a simple machine with one single block as a practice

**Comment by StarkDetail023** [comment]
I did do the singleblock but the recipes work the same there as well
where is the data for the mod stored?

**Comment by Yefancy** [comment]
there is a button to open the folder of mbd2 data while you are saving the projects

**Comment by Yefancy** [comment]
btw, lets move to the discord? gh is used for bug report instead of tuto help

**Comment by StarkDetail023** [comment]
alr, should I just put my discord friend info here?

**Comment by Yefancy** [comment]
nope multiblocked2 discord link is avaible on the curseforge/modrinth

**Comment by StarkDetail023** [comment]
alr I sent you a message
