### ISSUE TITLE
[bug] particle texture error at server？

### ISSUE THREAD

**Issue by QLNPLUS** [Low-Drag-MC/Multiblocked2#45]
高处坠落到机器上产生的粒子材质，在服务器中显示异常，单人模式中是正常的，视频大于10mb上传不了
![image](https://github.com/user-attachments/assets/d043fe9f-df9d-456c-b82b-c901797f6296)
![image](https://github.com/user-attachments/assets/65d5f792-aeda-4885-9108-61dc80ea4a17)

**Comment by Yefancy** [comment]
Thanks for your report. It got fixed with the latest mbd and ldlid
