### ISSUE TITLE
The machine does not produce ember energy while working on the recipe

### ISSUE THREAD

**Issue by fish1145** [Low-Drag-MC/Multiblocked2#47]
In the case of successful application of the formula, the machine does not produce ember energy, and some of the formulas produce ember energy.![Image_1729763486503](https://github.com/user-attachments/assets/33f93dc3-93ea-49f4-a4b0-113b32e30b5b)

**Comment by fish1145** [comment]
![Image_1729763489919](https://github.com/user-attachments/assets/b55a04f0-400e-4229-8476-1c55be78c06b)
![Image_1729763489919](https://github.com/user-attachments/assets/a0e36169-63ab-4f0c-ba20-1ea8f6f41c0e)
![Image_1729763488300](https://github.com/user-attachments/assets/efe000da-9a58-4f43-88fb-31e5b2b2b348)

**Comment by fish1145** [comment]
![Image_1729763491511](https://github.com/user-attachments/assets/b35f9549-a08e-4f0c-89f2-74af4a34ecf1)
![Image_1729763489919](https://github.com/user-attachments/assets/bdd4dea8-d7ab-4e33-84cd-ab82941482de)
![Image_1729763488300](https://github.com/user-attachments/assets/bdb59f4d-897f-4128-8e7c-505ed4455ff0)

**Comment by fish1145** [comment]
![Image_1729763486503](https://github.com/user-attachments/assets/718c2931-65ac-4ee1-9d8c-ca7b23a772c0)

**Comment by Yefancy** [comment]
没看懂问题 你要不说中文？或者群里@我

**Comment by Yefancy** [comment]
formulas是什么

**Comment by fish1145** [comment]
> 没看懂问题 你要不说中文？ 或者群里@我

就是我写了一个配方，配方里面产出有100的余烬能量， Ui什么的东西都是调好了，可是他产出0，对不起，我英语不太好，所以用的是机翻

**Comment by Yefancy** [comment]
可以发你的mbd2文件夹给我测测

**Comment by Yefancy** [comment]
你可以加mbd qq群交流块一点
