### ISSUE TITLE
Cancel recipe working event won't stop the recipe process

### ISSUE THREAD

**Issue by FalAut** [Low-Drag-MC/Multiblocked2#54]
Cancel the Before Recipe Working Event: machine still work

https://github.com/user-attachments/assets/2589f7f9-7bc3-49b4-8f4c-8431892f41f0

Cancel the Recipe Working Event: machine will skip recipe tick

https://github.com/user-attachments/assets/cae72b9b-d00b-474e-8614-9e46b0ae59b5

**Comment by Yefancy** [comment]
thanks for your report. fixed since the 1.0.16
