### ISSUE TITLE
Durability based items

### ISSUE THREAD

**Issue by redgamer229** [Low-Drag-MC/Multiblocked2#55]
durability based items don't get auto assigned to slots like normal items you have to tell it what slot to target in the recipe type creator.

**Comment by Yefancy** [comment]
what do you mean by auto assigned?

**Comment by redgamer229** [comment]
Most items when you add them show up in the import slots instantly without needing to be told to with a ui slot name. But with durability items they require a ui slot name to show up in the recipe
![2024-11-15_14 19 16](https://github.com/user-attachments/assets/b7c442a5-909a-46b5-87de-1d713bdf0bba)

**Comment by Yefancy** [comment]
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/0e06b290-fa68-4095-a693-aab6024d47ec">

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/4152d4c4-7fb7-4a16-b3e6-bf4f8195c767">


<img width="481" alt="image" src="https://github.com/user-attachments/assets/dfc74e04-c307-478f-b01d-5a059e7f850a">

sorry, I cant reproduce it, could you send me your mbd2 folder?

**Comment by redgamer229** [comment]
I didn't have my mods updated. It seems you have added a import for both types of items instead of them being on one import. So this bug has be fixed at some point without me realizing it.
