### ISSUE TITLE
Getting `ArrayIndexOutOfBoundsException` when loading a multiblock project

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#6]
### Description
I've created a dummy multiblock project and now I am unable to open it with the in-game editor as the game crashes. 

### Crash report
[crash-2024-09-26_13.09.39-client.txt](https://github.com/user-attachments/files/17146633/crash-2024-09-26_13.09.39-client.txt)

### Project file
[mb1.mb.zip](https://github.com/user-attachments/files/17146629/mb1.mb.zip)

**Comment by Yefancy** [comment]
should be fixed in the latest mbd2 (1.0.4+)
