### ISSUE TITLE
Breaking proxy part of a formed multiblock in survival destroys the original block that was in its place

### ISSUE THREAD

**Issue by yellowcake3d** [Low-Drag-MC/Multiblocked2#66]
If you make a multiblock that uses a model, and make predicates that disable render when formed, that proxy multiblock part block can be broken instantly in survival and nothing will drop.

Video example of the bug:
https://github.com/user-attachments/assets/992e0aa8-48d1-4623-a734-0427ac44ff89

**Comment by Yefancy** [comment]
fixed since 1.0.20
