### ISSUE TITLE
[CRASH] "this.patterns[this.index].predicateMap" is null

### ISSUE THREAD

**Issue by SheReyy** [Low-Drag-MC/Multiblocked2#67]
Forge: 47.3.0
JEI: 15.16.2.73
mbd2: 1.0.19.b
ldlib: 1.0.33.b

[Here](https://gist.github.com/SheReyy/36776211962c6ba9d3fd5ac1107aaf5a)'s the crash. Not sure if it's my fault, or not. I don't really know what I'm doing with the mod

This happened after I double clicked one of the blocks from the jei page that shows h\ow to build the multiblock.

**Comment by Yefancy** [comment]
it happens while an internal error occurs. could you remake your mahcine and test it with the latest mbd2? Send me your mbd2 folder and reopen the issue if it still crashes
