### ISSUE TITLE
"The game crashed whilst initializing game Error: java.lang.RuntimeException: null"

### ISSUE THREAD

**Issue by existereoracle** [Low-Drag-MC/Multiblocked2#7]
Mods are create, kubejs (and addons), mbd2.  All mods are up to date.

[crash-2024-09-27_11.42.14-client.txt](https://github.com/user-attachments/files/17166620/crash-2024-09-27_11.42.14-client.txt)

[latest.log](https://github.com/user-attachments/files/17166673/latest.log)

**Comment by Yefancy** [comment]
```
Suppressed: java.lang.IllegalStateException: [register] registry mbd2:machine_definition contains key mbd2:new_machine already
```

**Comment by Yefancy** [comment]
there are dupicated registry name. please remove machine project file with same registry name.

**Comment by existereoracle** [comment]
this seems to have fixed it, thank you!
