### ISSUE TITLE
Issues with predicates

### ISSUE THREAD

**Issue by andriihorpenko** [Low-Drag-MC/Multiblocked2#72]
## Description
This is a collection of issues with predicate sybsystem. Some issues are cosmetic, some cause crashes and other troubles.

## Project file
[ldlib.zip](https://github.com/user-attachments/files/18048233/ldlib.zip)

### Description
Structure preview has air blocks instead of actual blocks, while candidates list shows barriers instead of blocks.
### Investigation
Looks like the shape info for XEI mods is loaded before tags are available, causing all sort of troubles. Even though the `SimplePredicate#candidates` is a Supplier, it's getting resolved too early.
### Demo
The structure has 3 tag predicates of `minecraft:wool`, but it was resolved to barriers instead.
<img width="250" alt="image" src="https://github.com/user-attachments/assets/0d441664-6604-44ec-9522-fafd85a04b0f">

### Description
Using the same project file above, when you click on any block in XEI structure preview, the game crashes hinting that `patterns[this.index].predicateMap" is null`
### Investigation
The `predicateMap` is inited In `PatternPreviewWidget#initializePattern`, however, for some reason the `PatternMatchContext` has `predicates` key missing (the map is empty whatsoever), leading to NPE on access.
### Crash report
https://bytebin.lucko.me/xnYjxXlC9q
### Similar issues
https://github.com/Low-Drag-MC/Multiblocked2/issues/67

**Comment by Yefancy** [comment]
fixed since 1.0.20
