### ISSUE TITLE
Slots bug when re-entering the world

### ISSUE THREAD

**Issue by krupta** [Low-Drag-MC/Multiblocked2#8]
When I re-join the world, the items that were placed in one slot replace all the others.

![image](https://github.com/user-attachments/assets/0b4566cf-cf94-4b1a-bfd3-72df10d144b1)

And I can take them away 
![image](https://github.com/user-attachments/assets/30c20ad8-9e70-4ad8-b5d4-bb2197b9293b)

**Comment by Yefancy** [comment]
do you set a unique id for each slot trait?

**Comment by Yefancy** [comment]
if so, please share me all files under the mbd2 folder, I can help check it later

**Comment by krupta** [comment]
Yes, I have a unique ID set for each slot.

[mbd2.zip](https://github.com/user-attachments/files/17190493/mbd2.zip)

**Comment by Yefancy** [comment]
This is a serious bug that I just found out about. It has been fixed in the latest version (1.0.5.a+)
